export const SET_POPULAR = 'SET_POPULAR';
export const SET_LATEST = 'SET_LATEST';
export const ADD_TO_WATCHLIST = 'ADD_TO_WATCHLIST';
export const REMOVE_FROM_WATCHLIST = 'REMOVE_FROM_WATCHLIST';
export const REMOVE_FROM_WATCHLIST_FROM_WATCHLIST = 'REMOVE_FROM_WATCHLIST_FROM_WATCHLIST';